feat(footer component): style a footer component
202306-NEA-DZ-FEW/HopeHub pull request #22
Opened 2023-10-17 15:13 UTC by BrahimHM

#3

# Description

Please include a summary of the changes you made, files created, is it page or component, is it project set up

## Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

# Checklist:

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my own code
-   [ ] I have commented my code, particularly in hard-to-understand areas
-   [ ] I have added tests that prove my fix is effective or that my feature works

**Files changed**:
list all file names that were created or modified (components, configs, style)

-   global.css
-   \_api.js
-   ...etc

**Screenshots**:

2023-10-17 16:52 UTC, Zohir-kk requested changes
Overall it's a really well done job, but there are some minor remarks 
- I suggest a padding that is the same with one in the navbar something like px-5 will be great 
- For a visually appealing design I suggest we move the links to the far right and to be centered vertically
- Lastly I recommend we change the color of the text to the Neutral Black used in the design and remove the oppacity

2023-10-17 17:40 UTC, GhaniBahri commented
just for consistency ,footer component should be imported and used in 'Layout/Layout.jsx', same as the navBar component

2023-10-18 10:09 UTC, GhaniBahri approved these changes

2023-10-18 19:25 UTC, Zohir-kk approved these changes

2023-10-18 19:45 UTC, merged