feat(page): create a contact page and a form component
202306-NEA-DZ-FEW/HopeHub pull request #24
Opened 2023-10-17 17:19 UTC by Amel7400

# [Contact] #7

## Description

This pull request introduces changes related to the Contact page. It encompasses the following modifications:

- Created a Contact page with basic styling using Tailwind CSS.
- Developed a ContactForm component.
- Added translations for English, Arabic, and French to the ContactForm component.
- Created a snapshot test for the ContactForm component to ensure stability and reliability.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] I have added tests that prove my fix is effective or that my feature works.

## Files changed:

List of all file names created or modified (components, configs, style):

- Contact page (contact.js)
- ContactForm component (ContactForm.js)
- Translations for English, Arabic, and French (translation files)
- Snapshot test for ContactForm (ContactForm.test.js)
- Styling with tailwind css
- ...

**Screenshots**:
![contact](https://github.com/202306-NEA-DZ-FEW/HopeHub/assets/138016246/0e6974f0-55e3-46c2-b653-966240f8e486)

2023-10-17 17:46 UTC, Zohir-kk requested changes
Great work Amel 
- I suggest we use the Image tag instead of img as suggested by the eslint error in line 42 in contacts page
- run npm run format to pass prettier check,
if the page still need work, we should leave this PR open, until we finalise the page

2023-10-23 17:20 UTC, fketta approved these changes

2023-10-23 17:27 UTC, GhaniBahri requested changes
Great work, minor changes and it will be perfect

2023-10-23 17:27 UTC, GhaniBahri commented on public/assets/Background.png
this image already exist in develop, would you check and give it the same name!!

2023-10-23 17:27 UTC, GhaniBahri commented on src/components/ContactForm/ContactForm.jsx
it would be perfect to add redirect in handleSumbit, to take user to thanks page, you can check develop for the exact route path

2023-10-24 06:59 UTC, GhaniBahri approved these changes
I wish i coul find something to critic 🫢
Excellent job👍

2023-10-24 20:57 UTC, Zohir-kk approved these changes

2023-10-24 23:52 UTC, merged