Feature/user profile page
202306-NEA-DZ-FEW/HopeHub pull request #32
Opened 2023-10-22 19:59 UTC by BrahimHM

# Description

create the profile info page and just customize the styling and the multi-language

## Type of change

Please delete options that are not relevant.

-   [ ] Bug fix (non-breaking change which fixes an issue)
-   [ ] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
-   [ ] This change requires a documentation update

# Checklist:

-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my own code

**Files changed**:
list all file names that were created or modified (components, configs, style)

-   global.css
-pages/Profile/index.jsx
-public\locales\ar\common.json
-public\locales\fr\common.json
-public\locales\en\common.json

**Screenshots**:
![4](https://github.com/202306-NEA-DZ-FEW/HopeHub/assets/40490873/d70ae649-0d66-4a3d-b4b3-c4b159ed297b)
![Capture 2](https://github.com/202306-NEA-DZ-FEW/HopeHub/assets/40490873/b938f853-0d75-446a-916b-133625d9b5fa)
![Capture 3](https://github.com/202306-NEA-DZ-FEW/HopeHub/assets/40490873/0d16b5be-58e2-482e-ac6f-5c06c355603e)
![Captureprofile](https://github.com/202306-NEA-DZ-FEW/HopeHub/assets/40490873/286beb64-bf18-4472-a783-f6e6e55a3ce4)

2023-10-22 21:49 UTC, Zohir-kk requested changes
Nice work ibrahim, you just need to work on the conflicts you have and make sure the checks pass and you're good to go

2023-10-23 00:08 UTC, GhaniBahri commented
Excelent job, wouldn't expect less from you
few details need some double check, 
- the add image icon is not where it should be
- the background color doesn't match the design
- the bottom buttons might need some space and margin from the upper input and between label
otherwise it's perfect, keep up the energy
![pr1Capture](https://github.com/202306-NEA-DZ-FEW/HopeHub/assets/117347744/204b2bad-9e20-456d-8f53-7f471cbfe3c2)
![pr2Capture](https://github.com/202306-NEA-DZ-FEW/HopeHub/assets/117347744/13361c05-d68a-4589-9aa7-c5d9d6cc58f1)

2023-10-23 00:13 UTC, GhaniBahri requested changes
excelent job wouldn't expect less from you
just before merge few details must be updated:
- the add file icon is not where it should be
- it would be preferable if we add some space between labels and buttons, and margin to bottom buttons
otherwise everything is perfect, keep up the energy
![pr2Capture](https://github.com/202306-NEA-DZ-FEW/HopeHub/assets/117347744/7a6be207-0fef-4c18-88fd-6d5ca10075df)
![pr1Capture](https://github.com/202306-NEA-DZ-FEW/HopeHub/assets/117347744/168c39ff-2b54-4a3a-a5ba-c8998ce9a7a8)

2023-10-23 21:45 UTC, GhaniBahri approved these changes

2023-10-23 21:45 UTC, Zohir-kk approved these changes

2023-10-23 21:47 UTC, merged